if: branch != master AND type = push
language: node_js
node_js:
    - '10'
install:
    - git submodule update --init --recursive
    - yarn install --frozen-lockfile --network-concurrency 1
script:
    - npm run test -- --detectOpenHandles
    - npm run lint
    - npm run build:ci
cache:
    yarn: true
    directories:
        - node_modules
notifications:
    email: false
